"""add rejected_requests table

Revision ID: d2be24faea25
Revises: 26a459fadfed
Create Date: 2026-06-23 15:32:27.059322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2be24faea25'
down_revision: Union[str, Sequence[str], None] = '26a459fadfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('request_method', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejected_requests_api_key_id'), 'rejected_requests', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_rejected_requests_reason'), 'rejected_requests', ['reason'], unique=False)
    op.create_index(op.f('ix_rejected_requests_slug'), 'rejected_requests', ['slug'], unique=False)
    op.create_index(op.f('ix_rejected_requests_timestamp'), 'rejected_requests', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejected_requests_timestamp'), table_name='rejected_requests')
    op.drop_index(op.f('ix_rejected_requests_slug'), table_name='rejected_requests')
    op.drop_index(op.f('ix_rejected_requests_reason'), table_name='rejected_requests')
    op.drop_index(op.f('ix_rejected_requests_api_key_id'), table_name='rejected_requests')
    op.drop_table('rejected_requests')
    # ### end Alembic commands ###
